//! Cross-language wire contract — Rust side.
//!
//! Asserts this SDK puts BYTE-IDENTICAL HTTP requests on the wire as the
//! reference (TypeScript) SDK, for every op in the shared core surface. The
//! expectation is not written here: it is read from
//! `tests/sdk/ts-request-fixtures.json`, which `tests/sdk/contract.test.ts`
//! regenerates from the reference SDK on every run. See that file for the design.
//!
//! WHY THIS LIVES IN sdk/rust RATHER THAN tests/sdk: it rides the `cargo test`
//! job that already exists and already has the toolchain, so the gate cannot be
//! dropped by "the contract job doesn't have Rust installed". The four other
//! bindings each do the same inside their own suite.
//!
//! WHAT IT CATCHES:
//!
//!  1. A create field this SDK never puts on the wire. `resolution`/`record`/
//!     `volumes` were missing from `CreateOptions` for weeks with every test
//!     green, because the old fixture only held fields the test happened to pass.
//!     This one is MAXIMAL, so a missing field is a diff.
//!  2. A core op this SDK doesn't implement AT ALL. `coreOps` is iterated, and an
//!     op with no arm in the match below panics. That is how `pause`/`resume` are
//!     pinned: this SDK accepted `lifecycle.onTimeout:"pause"` while offering NO
//!     WAY to resume the VM it had just paused, and no per-field assertion would
//!     ever have noticed an ABSENCE.
//!  3. A field deleted from `CreateOptions`: this file sets every one of them, so
//!     removing one fails the BUILD before any assertion runs. In a language
//!     without reflection, the compiler is the reflection.
//!
//! The fake gateway is two listeners (REST + WS) rather than one: the control
//! channel dials with `tokio_tungstenite`, whose handshake wants the raw stream
//! from byte zero, so multiplexing it onto the recording HTTP socket would mean
//! hand-rolling the upgrade. Two ports is the honest, boring option — `resume`
//! genuinely reconnects.

use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use serde::Deserialize;
use serde_json::Value;
use solari::{Client, ClientOptions, CreateOptions, Lifecycle, VolumeAttachment};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;

/// The canonical wire contract, regenerated by the TS reference suite.
const CONTRACT_PATH: &str = "tests/ts-request-fixtures.json";

/// Mirrors the fixture's `sessionId`; asserted equal below so they cannot drift.
const CANONICAL_ID: &str = "pool-a:vm-7:org-42.sig";
const ENC_ID: &str = "pool-a%3Avm-7%3Aorg-42.sig";

/// The ops this binding implements, kept beside the `match` below. Asserted equal
/// to the contract's `coreOps`, so a new op in the contract fails here loudly
/// rather than being quietly skipped.
const IMPLEMENTED_OPS: &[&str] = &[
    "createSandbox",
    "createDesktop",
    "get",
    "pause",
    "resume",
    "kill",
];

#[derive(Debug, Deserialize)]
struct WireRequest {
    method: String,
    path: String,
    #[serde(default)]
    body: Option<Value>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct WireContract {
    session_id: String,
    core_ops: Vec<String>,
    requests: HashMap<String, WireRequest>,
}

#[derive(Debug, Clone)]
struct Recorded {
    method: String,
    path: String,
    body: Option<Value>,
}

fn load_contract() -> WireContract {
    // HARD FAIL, never skip. The fixture is committed; its absence means the
    // checkout is broken or the reference suite never ran — either way this test
    // proves nothing, and "proves nothing" must not read as "passed".
    let raw = std::fs::read_to_string(CONTRACT_PATH)
        .unwrap_or_else(|e| panic!("wire contract {CONTRACT_PATH} unreadable: {e}"));
    let c: WireContract = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("wire contract {CONTRACT_PATH} is not valid JSON: {e}"));
    assert!(
        !c.core_ops.is_empty() && !c.requests.is_empty(),
        "wire contract carries no coreOps/requests — it is not a contract"
    );
    c
}

/// A WS listener that completes the handshake and holds the socket open, so a
/// handle's post-resume reconnect really connects.
async fn start_ws_gateway() -> u16 {
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    tokio::spawn(async move {
        loop {
            let Ok((sock, _)) = listener.accept().await else {
                return;
            };
            tokio::spawn(async move {
                if let Ok(ws) = tokio_tungstenite::accept_async(sock).await {
                    // Hold it open; this suite asserts REST shapes, and the
                    // channel only needs to be genuinely connected.
                    let (_sink, mut read) = futures_util::StreamExt::split(ws);
                    while futures_util::StreamExt::next(&mut read).await.is_some() {}
                }
            });
        }
    });
    port
}

/// A recording REST listener returning the same canned shapes as the TS fake.
async fn start_rest_gateway(ws_port: u16) -> (u16, Arc<Mutex<Vec<Recorded>>>) {
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    let recorded: Arc<Mutex<Vec<Recorded>>> = Arc::new(Mutex::new(Vec::new()));
    let rec = recorded.clone();

    tokio::spawn(async move {
        let control_url = format!("ws://127.0.0.1:{ws_port}/control/{ENC_ID}");
        loop {
            let Ok((mut sock, _)) = listener.accept().await else {
                return;
            };
            let rec = rec.clone();
            let control_url = control_url.clone();
            tokio::spawn(async move {
                let mut buf = Vec::new();
                let mut tmp = [0u8; 2048];
                // Read headers, then exactly Content-Length bytes of body.
                let (head, body_raw) = loop {
                    let Ok(n) = sock.read(&mut tmp).await else { return };
                    if n == 0 {
                        return;
                    }
                    buf.extend_from_slice(&tmp[..n]);
                    if let Some(pos) = find_subslice(&buf, b"\r\n\r\n") {
                        let head = String::from_utf8_lossy(&buf[..pos]).to_string();
                        let clen = content_length(&head).unwrap_or(0);
                        let start = pos + 4;
                        while buf.len() < start + clen {
                            let Ok(n) = sock.read(&mut tmp).await else { return };
                            if n == 0 {
                                break;
                            }
                            buf.extend_from_slice(&tmp[..n]);
                        }
                        break (head, String::from_utf8_lossy(&buf[start..]).to_string());
                    }
                };

                let mut parts = head.split_whitespace();
                let method = parts.next().unwrap_or("").to_string();
                // The RAW, still-escaped path is the wire: decoding it here would
                // launder exactly the %3A-vs-: divergence this contract pins.
                let path = parts.next().unwrap_or("").to_string();
                let body: Option<Value> = if body_raw.trim().is_empty() {
                    None
                } else {
                    serde_json::from_str(body_raw.trim()).ok()
                };
                rec.lock().unwrap().push(Recorded {
                    method: method.clone(),
                    path: path.clone(),
                    body: body.clone(),
                });

                let payload = canned_response(&method, &path, body.as_ref(), &control_url, ws_port);
                let resp = format!(
                    "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
                    payload.len(),
                    payload
                );
                let _ = sock.write_all(resp.as_bytes()).await;
                let _ = sock.flush().await;
            });
        }
    });
    (port, recorded)
}

fn canned_response(
    method: &str,
    path: &str,
    body: Option<&Value>,
    control_url: &str,
    ws_port: u16,
) -> String {
    if method == "POST" && path == "/sandboxes" {
        let kind = body
            .and_then(|b| b.get("kind"))
            .and_then(|k| k.as_str())
            .unwrap_or("sandbox");
        let mut out = serde_json::json!({
            "sandboxId": CANONICAL_ID,
            "kind": kind,
            "controlUrl": control_url,
            "expiresAt": "2026-01-01T00:00:00Z",
        });
        if kind == "desktop" {
            out["streamUrl"] = Value::String(format!("ws://127.0.0.1:{ws_port}/stream/{ENC_ID}"));
        }
        return out.to_string();
    }
    if method == "POST" && path.ends_with("/pause") {
        return serde_json::json!({ "state": "paused" }).to_string();
    }
    if method == "POST" && path.ends_with("/resume") {
        // The session comes back on a FRESH slot, so the gateway hands back the
        // control URL to re-attach to.
        return serde_json::json!({ "state": "running", "controlUrl": control_url }).to_string();
    }
    if method == "GET" && path.starts_with("/sandboxes/") {
        return serde_json::json!({
            "sandboxId": CANONICAL_ID,
            "kind": "sandbox",
            "state": "running",
            "expiresAt": "2026-01-01T00:00:00Z",
        })
        .to_string();
    }
    serde_json::json!({ "ok": true }).to_string()
}

/// The maximal create DTO, field-for-field the TS reference's. EVERY field of
/// `CreateOptions` is set on purpose: deleting one breaks this build.
fn maximal_options() -> CreateOptions {
    CreateOptions {
        template: Some("base".into()),
        cpu: Some(2),
        mem_mb: Some(2048),
        disk_gb: Some(10),
        envs: Some(HashMap::from([("FOO".to_string(), "bar".to_string())])),
        metadata: Some(HashMap::from([("proj".to_string(), "alpha".to_string())])),
        timeout_ms: Some(600_000),
        from_snapshot: Some("snap_seed".into()),
        lifecycle: Some(Lifecycle {
            on_timeout: "pause".into(),
            auto_resume: Some(true),
        }),
        volumes: Some(vec![VolumeAttachment {
            volume_id: "vol_data".into(),
            path: "/data".into(),
        }]),
        resolution: None,
        record: None,
    }
}

#[tokio::test(flavor = "multi_thread")]
async fn wire_contract_matches_reference_sdk() {
    let contract = load_contract();
    assert_eq!(
        contract.session_id, CANONICAL_ID,
        "fixture sessionId != this suite's — the contract moved under us"
    );

    // A CHECKLIST THAT FAILS CLOSED.
    let mut have: Vec<String> = IMPLEMENTED_OPS.iter().map(|s| s.to_string()).collect();
    let mut want = contract.core_ops.clone();
    have.sort();
    want.sort();
    assert_eq!(
        have, want,
        "op table does not match the contract's coreOps. An op in the contract with no arm \
         below is a surface this binding is missing."
    );

    let ws_port = start_ws_gateway().await;
    let (rest_port, recorded) = start_rest_gateway(ws_port).await;
    let client = Client::new(ClientOptions::new(
        "key-test",
        format!("http://127.0.0.1:{rest_port}"),
    ))
    .unwrap();

    let mut sbx = None;

    for name in &contract.core_ops {
        let before = recorded.lock().unwrap().len();

        match name.as_str() {
            "createSandbox" => {
                sbx = Some(client.create(maximal_options()).await.expect("createSandbox"));
            }
            "createDesktop" => {
                let mut o = maximal_options();
                o.template = Some("default".into());
                o.resolution = Some("1280x720".into());
                o.record = Some(true);
                let d = client.create_desktop(o).await.expect("createDesktop");
                d.close();
            }
            "get" => {
                client.get(CANONICAL_ID).await.expect("get");
            }
            "pause" => {
                let s = sbx.as_ref().expect("no handle");
                s.pause().await.expect("pause");
                // Asserted here, not at the end: `kill` closes the channel too,
                // so a check after the loop would pass either way.
                assert!(!s.connected(), "pause: control channel still open");
            }
            "resume" => {
                let s = sbx.as_mut().expect("no handle");
                s.resume().await.expect("resume");
                assert!(
                    s.connected(),
                    "resume: control channel not re-opened on the fresh slot"
                );
            }
            "kill" => {
                sbx.as_ref().expect("no handle").kill().await.expect("kill");
            }
            other => panic!("{other}: NOT IMPLEMENTED in the Rust SDK op table"),
        }

        let made: Vec<Recorded> = recorded.lock().unwrap()[before..].to_vec();
        // An op that emitted nothing must never compare equal to anything.
        assert_eq!(
            made.len(),
            1,
            "{name}: emitted {} HTTP requests, want exactly 1",
            made.len()
        );
        let got = &made[0];
        let exp = contract
            .requests
            .get(name)
            .unwrap_or_else(|| panic!("{name}: absent from the contract's requests"));
        assert_eq!(
            (got.method.as_str(), got.path.as_str()),
            (exp.method.as_str(), exp.path.as_str()),
            "{name}: wire mismatch"
        );
        assert_eq!(got.body, exp.body, "{name}: body mismatch");
    }
}

fn find_subslice(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack.windows(needle.len()).position(|w| w == needle)
}

fn content_length(head: &str) -> Option<usize> {
    for line in head.lines() {
        if let Some(v) = line.to_lowercase().strip_prefix("content-length:") {
            return v.trim().parse().ok();
        }
    }
    None
}
